// <auto-generated />
namespace Web.ITroc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FK_For_Category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK_For_Category));
        
        string IMigrationMetadata.Id
        {
            get { return "201902131606426_FK_For_Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
